CREATE TABLE IF NOT EXISTS  users (
  id SERIAL NOT NULL PRIMARY KEY,
  login VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  score INTEGER DEFAULT 0
);